### ISSUE TITLE
Liquibase changelog file generation should not use work directory

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-data#20]
#### Changes
- Liquibase master changelog stored in memory now.
- Spring boot version updated: 2.4.0 -> 2.4.2
- Liquibase version updated: 3.10.3 (spring boot dependency version) -> 4.2.2

#### QA Notes:

1. Create application, 
2. add some entities,
3. run.

**ER:**
- eihter no `*liquibase-changelog.xml` created in work dir. (`jmix.core.workDir` property, usually it is `.jmix/work`) or whole `.jmix/work` is absent while `jmix.core.workDir` is not overriden in application.properties

**Comment by knstvk** [comment]
Before your changes, there was a static `create` method that was used in additional data store config beans:
```
    @Bean
    public SpringLiquibase ds1Liquibase(LiquibaseChangeLogProcessor processor) {
        return JmixLiquibase.create(ds1DataSource(), new LiquibaseProperties(), processor, "ds1");
    }
```
What should we use now?

**Comment by dtaimanov** [comment]
This method is still [here](https://github.com/Haulmont/jmix-data/blob/master/data-autoconfigure/src/main/java/io/jmix/autoconfigure/data/JmixLiquibaseCreator.java). `JmixLiquibase` has been renamed to `JmixLiquibaseCreator` in order to use name `JmixLiquibase` for class extending `SpringLiquibase`.
